# Nome da pipeline
name: Run Basic Tests - Scheduler

# Em que momento será executada [push] ou pull_request:[master]
on:
 schedule:
    - cron: '0 20,22,23 * * 1,5'

jobs:
# o que será feito nessa pipeline
# só teremos um job: rodas os testes
  cypress-run:
    # máquina que será executada
    runs-on: ubuntu-latest

    # é o passo a passo para podermos configurar tudo e poder rodas nossos testes
    steps:
      # Clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # Exemplo de execução no terminal
      - name: instalar dependencias do projeto
        run: npm install

      # Execução e configuração do projeto
      - name: Run Tests
        uses: cypress-io/github-action@v6
        with: 
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
